### ISSUE TITLE
Initial build of MFS application

### ISSUE THREAD

**Issue by PuloV** [PuloV/mfs#1]
Implement the base structure of the MFS application

**TODO**

- [ ] Use latest Ruby and RoR versions
- [ ] Research how to access the Google sheet using 
  - [ ] https://github.com/gimite/google-drive-ruby
  - [ ] https://www.twilio.com/en-us/blog/google-spreadsheets-ruby-html
- [ ] Use local-file DB
- [ ] Have a rake task that fetches data from google and transforms it to the local-file DB.
